---
- name: Initiating service stop request
  hosts: master
  tasks:
    - name: Stopping cookbook service
      community.docker.docker_stack:
        name: cookbook
        state: absent
        compose:
          - /data/primary/compose/cookbook/cookbook.yml



- name: Backup process started
  hosts: backup
  tasks:
    - name: Initiating cookbook backup
      become: yes
      shell: rclone --config /home/worker01/.config/rclone/rclone.conf sync /data/primary/docker/cookbook gdrive:/Backup/container_data/cookbook

- name: Getting cookbook service back to run
  hosts: master
  tasks:
    - name: Starting cookbook service
      community.docker.docker_stack:
        name: cookbook
        state: present
        compose:
          - /data/primary/compose/cookbook/cookbook.yml
